apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defvault-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - defvault.example.com
    secretName: defvault-tls
  rules:
  - host: defvault.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: defvault-backend-service
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: defvault-frontend-service
            port:
              number: 5173
